-- ==========================================================================================
-- PROJETO CHRONOS DTN - MODELO DE DADOS E PROCEDIMENTO DE CORREÇÃO RELATIVÍSTICA LUNAR
-- ORACLE DATABASE SQL & PL/SQL DDL / DML SCRIPT
-- ==========================================================================================

-- Exclui tabelas anteriores caso já existam para garantir uma recriação limpa do ambiente de banco de dados.
-- DROP TABLE T_CDTN_LEDGER_SYNC CASCADE CONSTRAINTS;
-- DROP TABLE T_CDTN_TRANSACTION_BUFFER CASCADE CONSTRAINTS;
-- DROP TABLE T_CDTN_DYNAMIC_ROUTES CASCADE CONSTRAINTS;
-- DROP TABLE T_CDTN_DELAY_LOGS CASCADE CONSTRAINTS;
-- DROP TABLE T_CDTN_ASSET_BALANCES CASCADE CONSTRAINTS;
-- DROP TABLE T_CDTN_NODE_REGISTRY CASCADE CONSTRAINTS;

-- 1. TABELA DE REGISTRO DE NÓS DE REDE (TERRA / LUA / SATÉLITE)
-- Armazena o cadastro de todos os gateways/nós ativos no sistema DTN de comunicação espacial.
CREATE TABLE T_CDTN_NODE_REGISTRY (
    -- ID sequencial único identificador do nó físico de rede interplanetária.
    id_node NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Nome descritivo legível do nó para auditoria (ex: "Lunar-Gateway-Alpha").
    name VARCHAR2(100) NOT NULL,
    -- Localização geográfica/espacial do nó (ex: "LUNAR_SOUTH_POLE", "EARTH_KSC").
    location VARCHAR2(50) NOT NULL,
    -- Endereço de rede ou protocolo utilizado para conexão física/lógica.
    network_address VARCHAR2(100) UNIQUE NOT NULL,
    -- Data de ativação do nó no sistema de gateway.
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- 2. TABELA DE SALDOS DE ATIVOS ESTÁVEIS (STABLECOINS TOKENIZADAS)
-- Controla a liquidez das stablecoins mapeadas (como USDC e USDT) autorizadas para liquidação.
CREATE TABLE T_CDTN_ASSET_BALANCES (
    -- ID identificador único do saldo e ativo correspondente.
    id_asset NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ID do nó de rede associado que retém a custódia local ou autoridade.
    id_node NUMBER NOT NULL,
    -- Símbolo de mercado do ativo digital de pareamento fiduciário (ex: "USDC", "USDT").
    symbol VARCHAR2(10) NOT NULL,
    -- Saldo atual líquido disponível no ledger local do nó de rede.
    balance NUMBER(18, 6) DEFAULT 0.000000 NOT NULL,
    -- Data e hora da última atualização de saldo.
    last_update TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    -- Chave estrangeira que garante a consistência referencial ao nó correspondente.
    CONSTRAINT fk_asset_node FOREIGN KEY (id_node) REFERENCES T_CDTN_NODE_REGISTRY(id_node)
);

-- 3. TABELA DOS REGISTROS DE ATRASOS E LATÊNCIAS DE SINAL (TELEMETRIA DTN)
-- Registra as métricas de latência medidas continuamente na rede espacial.
CREATE TABLE T_CDTN_DELAY_LOGS (
    -- Identificador único do log de telemetria de latência.
    id_delay NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identificador do nó que originou a telemetria do ping de comunicação.
    source_node NUMBER NOT NULL,
    -- Identificador do nó de destino da comunicação espacial.
    target_node NUMBER NOT NULL,
    -- Latência registrada em milissegundos (ex: 1280.0 para distância lunar de 1.28s).
    latency_ms NUMBER(10, 2) NOT NULL,
    -- Data e hora da coleta da telemetria de sinal da rede.
    logged_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    -- Restrições de chaves estrangeiras associadas ao cadastro de nós.
    CONSTRAINT fk_delay_source FOREIGN KEY (source_node) REFERENCES T_CDTN_NODE_REGISTRY(id_node),
    CONSTRAINT fk_delay_target FOREIGN KEY (target_node) REFERENCES T_CDTN_NODE_REGISTRY(id_node)
);

-- 4. TABELA DE ROTAS DINÂMICAS DE ROTEAMENTO ESPACIAL
-- Mapeia a topologia e disponibilidade de rotas ativas de comunicação por satélites de retransmissão.
CREATE TABLE T_CDTN_DYNAMIC_ROUTES (
    -- Identificador único da rota lógica definida na topologia interplanetária.
    id_route NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identificador do nó de origem da rota.
    source_node NUMBER NOT NULL,
    -- Identificador do nó de destino da rota.
    target_node NUMBER NOT NULL,
    -- Status atual de conectividade da rota ("ACTIVE", "OFFLINE_SHADOW", "DEGRADED").
    status VARCHAR2(20) NOT NULL,
    -- Largura de banda estimada disponível no canal de rádio ou laser espacial.
    bandwidth_kbps NUMBER(12, 2) NOT NULL,
    -- Chaves estrangeiras de amarração de topologia de nós.
    CONSTRAINT fk_route_source FOREIGN KEY (source_node) REFERENCES T_CDTN_NODE_REGISTRY(id_node),
    CONSTRAINT fk_route_target FOREIGN KEY (target_node) REFERENCES T_CDTN_NODE_REGISTRY(id_node)
);

-- 5. BUFFER TEMPORÁRIO DE TRANSAÇÕES DTN (STORE-AND-FORWARD)
-- Mantém as transações retidas durante a queda de sinal até que haja sincronização ativa.
CREATE TABLE T_CDTN_TRANSACTION_BUFFER (
    -- ID sequencial único da transação armazenada em cache temporário.
    id_tx NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identificador do nó emissor (geralmente nó lunar offline).
    source_node NUMBER NOT NULL,
    -- Identificador do nó receptor (geralmente gateway terrestre).
    target_node NUMBER NOT NULL,
    -- Carga útil contendo a transação em formato JSON (ex: valores, chaves, stablecoin).
    payload VARCHAR2(4000) NOT NULL,
    -- Timestamp com precisão de microssegundos gravado no relógio local do emissor.
    local_timestamp TIMESTAMP(6) NOT NULL,
    -- Status do processamento da fila ("PENDING", "PROCESSING", "ACKNOWLEDGED", "FAILED").
    sync_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    -- Registro da data de inserção no buffer local do gateway.
    buffered_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    -- Chaves de relacionamento lógico com nós.
    CONSTRAINT fk_tx_source FOREIGN KEY (source_node) REFERENCES T_CDTN_NODE_REGISTRY(id_node),
    CONSTRAINT fk_tx_target FOREIGN KEY (target_node) REFERENCES T_CDTN_NODE_REGISTRY(id_node)
);

-- 6. LIVRO RAZÃO CONSOLIDADO E SINCRONIZADO (LEDGER CENTRALIZADO)
-- Registro final definitivo e imutável das transações liquidadas na Terra com o tempo corrigido.
CREATE TABLE T_CDTN_LEDGER_SYNC (
    -- ID único global do registro consolidado no ledger financeiro.
    id_ledger NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ID de referência da transação de origem vinda do buffer.
    id_tx_ref NUMBER UNIQUE NOT NULL,
    -- Timestamp gravado originalmente na Lua (com aceleração temporal local).
    lunar_timestamp TIMESTAMP(6) NOT NULL,
    -- Timestamp corrigido pelo algoritmo relativístico sincronizado com o tempo terrestre.
    corrected_timestamp TIMESTAMP(6) NOT NULL,
    -- Desvio acumulado calculado em microssegundos no instante da transação.
    drift_microseconds NUMBER NOT NULL,
    -- Data de processamento e conciliação do registro financeiro na Terra.
    synced_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    -- Chave estrangeira ligando o livro-razão ao buffer original.
    CONSTRAINT fk_ledger_tx FOREIGN KEY (id_tx_ref) REFERENCES T_CDTN_TRANSACTION_BUFFER(id_tx)
);

-- ==========================================================================================
-- PROCEDURE PL/SQL DE CORREÇÃO DE DESVIO DE TEMPO RELATIVÍSTICO
-- ==========================================================================================

CREATE OR REPLACE PROCEDURE SP_CORRIGIR_TEMPO_LUNAR (
    -- Parâmetro de entrada: ID da transação a ser conciliada e corrigida.
    p_id_tx IN NUMBER,
    -- Parâmetro de saída: Status do processamento da transação (ex: "SUCCESS" ou mensagem de erro).
    p_status OUT VARCHAR2
) AS
    -- Declaração das variáveis locais necessárias para os cálculos matemáticos relativísticos.
    
    -- Armazena o registro do buffer a ser processado.
    v_lunar_time TIMESTAMP(6);
    -- Armazena o nó de origem para saber se realmente veio da Lua.
    v_source_node NUMBER;
    -- Localização geográfica do nó de origem.
    v_location VARCHAR2(50);
    -- Ponto de referência inicial comum (Epoch de Referência: 01-JAN-2026 00:00:00 UTC).
    v_epoch_ref TIMESTAMP(6) := TO_TIMESTAMP('2026-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS');
    -- Segundos decorridos desde a data de referência até o momento da transação.
    v_elapsed_seconds NUMBER;
    -- Drift total calculado em microssegundos com base no tempo decorrido.
    v_drift_us NUMBER;
    -- Fração de dia decorrida para aplicar a constante diária de dilatação.
    v_elapsed_days NUMBER;
    -- Timestamp final após subtração do desvio temporal acumulado na Lua.
    v_corrected_time TIMESTAMP(6);
    
    -- Constante de dilatação gravitacional da Lua (Einstein's General Relativity).
    -- O tempo na Lua passa 56 microssegundos mais rápido por dia terrestre (86.400 segundos).
    -- Constante diária = 56.000000 microssegundos.
    v_dilatation_per_day CONSTANT NUMBER := 56.000000;
    
BEGIN
    -- Busca os dados básicos da transação no buffer de transmissão temporário.
    SELECT local_timestamp, source_node
    INTO v_lunar_time, v_source_node
    FROM T_CDTN_TRANSACTION_BUFFER
    WHERE id_tx = p_id_tx;
    
    -- Busca a localização espacial do nó de origem para validar a aplicação da dilatação.
    SELECT location
    INTO v_location
    FROM T_CDTN_NODE_REGISTRY
    WHERE id_node = v_source_node;
    
    -- Se o nó gerador da transação estiver na Lua ("LUNAR_SOUTH_POLE", "LUNAR_ORBIT" etc), aplica correção.
    IF v_location LIKE 'LUNAR%' THEN
    
        -- Calcula o intervalo de tempo decorrido entre o timestamp lunar e a época terrestre de referência.
        -- O cálculo extrai o número de dias e converte em segundos para maior precisão matemática.
        v_elapsed_days := CAST(v_lunar_time AS DATE) - CAST(v_epoch_ref AS DATE);
        
        -- Garante que não trabalhamos com tempo negativo caso o registro seja anterior à Epoch de Referência.
        IF v_elapsed_days < 0 THEN
            v_elapsed_days := 0;
        END IF;
        
        -- Calcula o desvio acumulado: dias decorridos multiplicados pela taxa de aceleração diária (56 us/dia).
        v_drift_us := v_elapsed_days * v_dilatation_per_day;
        
        -- Aplica a correção física relativística:
        -- Subtrai o desvio acumulado em microssegundos (convertido para fração de dia) do timestamp local lunar.
        -- Como 1 segundo tem 1.000.000 de microssegundos, dividimos o drift por 1.000.000 para converter a segundos.
        -- Posteriormente dividimos por 86.400 (segundos de um dia) para obter a fração de dia a ser subtraída na data.
        v_corrected_time := v_lunar_time - NUMTODSINTERVAL(v_drift_us / 1000000.0, 'SECOND');
        
    ELSE
        -- Se a transação originou-se na Terra, não existe desvio gravitacional relativístico a ser mitigado.
        v_corrected_time := v_lunar_time;
        v_drift_us := 0.000000;
    END IF;
    
    -- Salva o registro financeiro definitivo conciliado na tabela do Livro-Razão global (Ledger).
    INSERT INTO T_CDTN_LEDGER_SYNC (
        id_tx_ref,
        lunar_timestamp,
        corrected_timestamp,
        drift_microseconds,
        synced_at
    ) VALUES (
        p_id_tx,
        v_lunar_time,
        v_corrected_time,
        v_drift_us,
        SYSTIMESTAMP
    );
    
    -- Atualiza o status do buffer de transações temporário para indicar consolidação bem-sucedida.
    UPDATE T_CDTN_TRANSACTION_BUFFER
    SET sync_status = 'ACKNOWLEDGED'
    WHERE id_tx = p_id_tx;
    
    -- Define o status de retorno da procedure como processamento bem-sucedido.
    p_status := 'SUCCESS';
    
EXCEPTION
    -- Captura erros de violação de restrições ou outras falhas de banco de dados para evitar travar a API.
    WHEN OTHERS THEN
        -- Grava o status de falha com a mensagem interna do SQLCODE e SQLERRM.
        p_status := 'ERROR: ' || SQLERRM;
        
        -- Atualiza o status do buffer para processamento com falha, permitindo retentativa pelo gateway DTN.
        UPDATE T_CDTN_TRANSACTION_BUFFER
        SET sync_status = 'FAILED'
        WHERE id_tx = p_id_tx;
        
        -- Propaga a transação de rollback implicitamente se necessário no ambiente chamador.
        COMMIT;
END SP_CORRIGIR_TEMPO_LUNAR;
/
